name: build-check

on:
  push:
    branches:
      - master

jobs:
  docker-build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: false
          tags: portfolio-svelte:test
          secrets: |
            "BASIC_AUTH_PASSWORD=${{ secrets.BASIC_AUTH_PASSWORD }}"
            "BASIC_AUTH_USERNAME=${{ secrets.BASIC_AUTH_USERNAME }}"
            "NTFY_URL=${{ secrets.NTFY_URL }}"
            "RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}"
            "PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.PUBLIC_RECAPTCHA_SITE_KEY }}"
            "PUBLIC_GITHUB_API_URL=${{ secrets.PUBLIC_GITHUB_API_URL }}"
            "PUBLIC_GITHUB_USERNAME=${{ secrets.PUBLIC_GITHUB_USERNAME }}"
