name: build-check

on:
  push:
    branches:
      - master

jobs:
  docker-build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: false
          tags: portfolio-svelte:test
          secrets: |
            ENVFILE=${{ secrets.ENVFILE }}
