name: release-please
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  docker-build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: false
          tags: portfolio-svelte:test
          secrets: |
            ENVFILE=${{ secrets.ENVFILE }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

  release-please:
    runs-on: ubuntu-latest
    needs: docker-build-check
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: node
